{{- range $name, $service := .Values.services }}
{{- if not $service.isWorker }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-svc
spec:
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ $service.port }}
---
{{- end }}
{{- end }}
